trigger:
  - staging

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: bin/build
        displayName: Build IZR Files
      - bash: bin/publish
        displayName: Publish IZR Files
      - task: CloudFoundryCLIInstall@0
        displayName: Prep Cloud Foundry CLI
        inputs:
          cfVersion: 6.51.0
      - task: CloudFoundry@1
        displayName: Deploy
        inputs:
          cfEndpoint: PCFone
          org: group-steeltoe
          space: initializr
          deploymentOptions: manifest
          cfManifest: deploy/cloud-foundry/manifest.yaml
        condition:
          and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/staging'), not(eq(variables['build.reason'], 'PullRequest')))
